/**
 * Word-by-word meanings for the transliterations, so a learner can hover any
 * word in a phrase and see what that word is doing there.
 *
 * Only the words the starter table does not already define on its own live
 * here. A card whose transliteration is a single word is its own definition —
 * "khamse" is glossed by the card that teaches five — and `src/utils/glossary`
 * reads those straight out of the seed. What is left is everything that only
 * ever appears inside a phrase: particles, prepositions, possessive endings,
 * conjugated verbs and the first half of a construct pair.
 *
 * House style for an entry:
 *
 * - Say what the *word* means, not what the phrase means. `ṣabāḥ` is "morning",
 *   even though the only card it appears on is "good morning".
 * - Mark who a form belongs to in parentheses — "(f)", "(to a man)" — because
 *   these two languages carry that in the ending, which is exactly what a
 *   learner is hovering the word to see.
 * - Keep it to a few words. This is read in a tooltip, over a card, mid-drill.
 */

export type GlossLanguage = 'hebrew' | 'arabic';

/**
 * Prefixes written onto the next word with a hyphen.
 *
 * `…` stands in for the stem's own meaning, so "ve-arba" reads as "and four"
 * without the table listing every numeral twice. Only hyphenated prefixes are
 * split off: a bare `la` is the Hebrew word for "to her", and `min` is a word
 * in its own right, so neither may be treated as a piece of something longer.
 */
export const CLITICS: Record<GlossLanguage, Record<string, string>> = {
  hebrew: {
    ve: 'and …',
    v: 'and …',
    u: 'and …',
    ha: 'the …',
    be: 'in …',
    ba: 'in the …',
    la: 'to the …',
    le: 'to …',
    mi: 'from …',
    me: 'from …',
    she: 'that …',
    ke: 'like …',
  },
  arabic: {
    w: 'and …',
    wa: 'and …',
    u: 'and …',
    // The article, and the shapes it takes when it assimilates to the letter
    // after it: il-bēt, but in-nūr and is-sāʿa. The vowel is written i-
    // throughout because that is what Palestinian says; as- survives only in
    // the frozen greeting as-salāmu ʿalaykum.
    il: 'the …',
    in: 'the …',
    is: 'the …',
    ish: 'the …',
    id: 'the …',
    it: 'the …',
    iz: 'the …',
    ir: 'the …',
    as: 'the …',
    la: 'to …',
    lal: 'to the …',
    bi: 'with …',
    bil: 'in the …',
    bish: 'in the …',
    ʿa: 'at …',
    ʿal: 'at the …',
    ʿas: 'at the …',
    ʿash: 'at the …',
  },
};

/**
 * The hand-written half of the glossary, keyed by the lower-cased word exactly
 * as the starter table romanises it.
 *
 * An entry here beats the meaning derived from a single-word card, because it
 * is written about the word itself where the derived one can only repeat
 * whatever the whole card happened to mean.
 */
export const CURATED_GLOSSES: Record<GlossLanguage, Record<string, string>> = {
  hebrew: {
    // --- particles, pronouns and the small joining words --------------------
    yesh: 'there is / has',
    ein: 'there is no',
    li: 'to me — with yesh, "I have"',
    la: 'to her — with yesh, "she has"',
    lo: 'not / no',
    // אל and על both come out as "al" once the silent ע is dropped, so the one
    // entry has to carry both words.
    al: 'on / about — and "do not" before a command',
    o: 'or',
    im: 'with',
    gam: 'also',
    kan: 'here',
    eize: 'which / what',
    // Also the imperative "get up", which a card teaches; a learner meeting it
    // inside a phrase is asking about the question word every time.
    kama: 'how much / how many',
    "me'od": 'very',
    "me'eifo": 'where from',
    mikan: 'from here',
    lesham: 'to there',
    akharei: 'after',
    efshar: 'is it possible / may I',
    "le'at": 'slowly',

    // --- endings that carry who is being spoken to or about -----------------
    lekha: 'to you (m)',
    lakh: 'to you (f)',
    elekha: 'to you (m)',
    elayikh: 'to you (f)',
    alekha: 'upon you (m)',
    alayikh: 'upon you (f)',
    alay: 'on me / for me',
    alekhem: 'upon you (pl)',
    atsmekha: 'yourself (m)',
    atsmekh: 'yourself (f)',
    shlomkha: 'your wellbeing (m)',
    shlomekh: 'your wellbeing (f)',
    shelanu: 'our',
    shelakhem: 'your (m pl)',
    shelakhen: 'your (f pl)',
    shelahem: 'their (m)',
    shelahen: 'their (f)',
    akhi: 'my brother',
    akhoti: 'my sister',

    // --- the numbers that only count masculine nouns -------------------------
    // "One to ten" teaches counting, which in Hebrew is the feminine column, so
    // these are no longer single-word cards and stopped glossing themselves.
    // They still appear inside every compound — esrim ve-shnayim — and a
    // learner hovering one there is asking precisely why it is not the shtayim
    // she was taught. Written out rather than left to derive from the "(with a
    // noun)" cards, which would answer "two (with a noun)" without saying which
    // noun, and would leave shnayim with no meaning at all.
    ekhad: 'one — counting masculine nouns',
    shnayim: 'two — counting masculine nouns',
    shlosha: 'three — counting masculine nouns',
    "arba'a": 'four — counting masculine nouns',
    khamisha: 'five — counting masculine nouns',
    shisha: 'six — counting masculine nouns',
    "shiv'a": 'seven — counting masculine nouns',
    shmona: 'eight — counting masculine nouns',
    "tish'a": 'nine — counting masculine nouns',
    asara: 'ten — counting masculine nouns',

    // --- times of day, days and the calendar --------------------------------
    boker: 'morning',
    tsohorayim: 'noon',
    hatsahorayim: 'the afternoon',
    erev: 'evening',
    layla: 'night',
    yom: 'day',
    tovim: 'good (pl)',
    maksim: 'delightful',
    "na'im": 'pleasant',
    nishma: 'is heard',
    khalomot: 'dreams',
    paz: 'gold — here "sweet"',
    rishon: 'first',
    sheni: 'second',
    shlishi: 'third',
    "revi'i": 'fourth',
    khamishi: 'fifth',
    shishi: 'sixth',
    sof: 'end',
    "hasha'a": 'the hour / the time',
    hitkhil: 'it began',
    zman: 'time',

    // --- greetings and set phrases ------------------------------------------
    barukh: 'blessed (m)',
    brukha: 'blessed (f)',
    haba: 'the one coming (m)',
    "haba'a": 'the one coming (f)',
    hashav: 'the one returning (m)',
    hashava: 'the one returning (f)',
    hashem: 'God — literally "the Name"',
    elohim: 'God',
    yishmor: 'may he protect',
    tishmor: 'guard / keep (to a man)',
    tishmeri: 'guard / keep (to a woman)',
    "be'ezrat": 'with the help of',
    mazal: 'luck',
    huledet: 'birth',
    khag: 'festival',
    "refu'a": 'healing',
    shlema: 'complete (f)',

    // --- asking and answering -----------------------------------------------
    "kor'im": 'they call — with li, "my name is"',
    mali: 'Mali — a name',
    tukhal: 'can you (m)',
    tukhli: 'can you (f)',
    lakhzor: 'to repeat / go back',
    daber: 'speak (to a man)',
    dabri: 'speak (to a woman)',
    "lish'ol": 'to ask',
    ivrit: 'Hebrew — the language',
    aravit: 'Arabic — the language',
    anglit: 'English — the language',
    yehudi: 'Jewish (m)',
    yehudiya: 'Jewish (f)',
    aravi: 'Arab (m)',
    araviya: 'Arab (f)',

    // --- family and people ---------------------------------------------------
    zug: 'pair — with bat or ben, "partner"',
    akhim: 'brothers',
    yeladim: 'children',
    khaverim: 'friends',
    krovei: 'relatives of',
    hamishpakha: 'the family',
    "nesu'a": 'married (f)',
    nasui: 'married (m)',
    mishehu: 'someone',
    orekhet: 'arranger (f) — with din, "lawyer"',
    orekh: 'arranger (m) — with din, "lawyer"',
    din: 'law',

    // --- the day's actions ----------------------------------------------------
    okhelet: 'eats (f)',
    okhel: 'eats (m)',
    arukhat: 'meal of',
    metsakhtsakhat: 'brushes (f)',
    metsakhtseakh: 'brushes (m)',
    shinayim: 'teeth',
    mivreshet: 'brush',
    mishkhat: 'paste of',
    khozeret: 'returns (f)',
    khozer: 'returns (m)',
    habayta: 'homewards',
    habayit: 'the house',
    babayit: 'in the house',
    beit: 'house of',
    "la'avoda": 'to work',
    muzika: 'music',
    makshiva: 'listens (f)',
    makshiv: 'listens (m)',
    nifgeshet: 'meets (f)',
    nifgash: 'meets (m)',
    gozeret: 'cuts (f)',
    gozer: 'cuts (m)',
    tsiporanayim: 'nails',
    khadar: 'room of',
    kosher: 'fitness',
    ambatya: 'bath',
    shena: 'sleep',
    bgadim: 'clothes',
    "shi'urei": 'lessons of',

    // --- things around the house ----------------------------------------------
    niyar: 'paper',
    toalet: 'toilet',
    giluakh: 'shaving',
    khomrei: 'materials of',
    nikuy: 'cleaning',
    mekhonat: 'machine of',
    hagana: 'protection',
    adama: 'earth — with tapuakh, "potato"',
    hakheshbon: 'the bill',
    nayad: 'portable',
    mispar: 'number',
    kolit: 'voice- (f)',
    sikha: 'call',
    "ne'enta": 'was answered',

    // --- feeling unwell --------------------------------------------------------
    khola: 'ill (f)',
    khole: 'ill (m)',
    kholim: 'the sick',
    hakholim: 'the sick',
    mirkakhat: 'pharmacy — in beit mirkakhat',
    "ko'ev": 'hurts (m)',
    "ko'evet": 'hurts (f)',
    harosh: 'the head',
    habeten: 'the stomach',
    "shi'ul": 'cough',
    skharkhoret: 'dizziness',
    margisha: 'feel (f)',
    margish: 'feel (m)',

    // --- trouble and help -------------------------------------------------------
    "ta'azor": 'help (to a man)',
    "ta'azri": 'help (to a woman)',
    "la'azor": 'to help',
    lamishtara: 'to the police',
    titkasheri: 'call (to a woman)',
    srefa: 'fire',
    nifga: 'is hurt',
    "le'ibud": 'lost — with halakhti, "I got lost"',
    "tid'ag": 'worry (m)',
    "tid'agi": 'worry (f)',
    khake: 'wait (to a man)',
    khaki: 'wait (to a woman)',
    "te'udat": 'certificate of',
    zehut: 'identity',

    // --- getting around ----------------------------------------------------------
    takhanat: 'station of',
    pne: 'turn (to a man)',
    pni: 'turn (to a woman)',
    sa: 'drive on (to a man)',
    "si'i": 'drive on (to a woman)',
    haramzor: 'the traffic light',
    pkak: 'stopper — with tnua, "traffic jam"',
    tnua: 'traffic',
    khagorat: 'belt of',
    betikhut: 'safety',
    sde: 'field of',
    "te'ufa": 'aviation',
    "magi'im": 'one gets to',
    knesset: 'assembly — in beit knesset, "synagogue"',
    ole: 'costs',
    limdod: 'to try on',
    mekhonit: 'car',

    // --- colours and describing things ---------------------------------------------
    tseva: 'colour',
    "ha'ahuv": 'the favourite',
    hashamayim: 'the sky',
    kkhulim: 'blue (pl)',
    einayim: 'eyes',
    yerukot: 'green (f pl)',
    zayit: 'olive',
    gur: 'cub — with klavim, "puppy"',
    klavim: 'dogs',

    // --- wanting, feeling, being able ------------------------------------------------
    rotsot: 'want (f pl)',
    rotsim: 'want (m pl)',
    yekhola: 'can (f)',
    yakhol: 'can (m)',
    "le'ekhol": 'to eat',
    lalekhet: 'to go',
    "mitga'aga'at": 'missing (f)',
    "mitga'age'a": 'missing (m)',

    // --- telling somebody to do something ------------------------------------
    // Everyday Hebrew gives its orders in the future tense, and the ending is
    // the person being told — which is the whole point of the cards these
    // words come from.
    tishtefi: 'wash (to a woman)',
    tishtof: 'wash (to a man)',
    tetsakhtsekhi: 'brush (to a woman)',
    tetsakhtseakh: 'brush (to a man)',
    tokhli: 'eat (to a woman)',
    tokhal: 'eat (to a man)',
    takhzeri: 'come back (to a woman)',
    takhzor: 'come back (to a man)',
    lekh: 'go (to a man)',
    lishon: 'to sleep',

    // --- the phrase decks ----------------------------------------------------
    // Everything below appears only inside a whole phrase. The endings are
    // tagged the same way as above: (f) / (m) is the speaker's own, and
    // "(to a woman)" / "(to a man)" is the person being spoken to.
    en: 'there is no',
    raba: 'much / many',
    nora: 'terrible',
    meshane: 'matters / makes a difference',
    "mitsta'eret": 'sorry (f)',
    "mitsta'er": 'sorry (m)',
    "ha'ezra": 'the help',
    sheken: 'that yes',
    khoshevet: 'thinking (f)',
    khoshev: 'thinking (m)',
    yoter: 'more',
    od: 'still / more',
    adayin: 'still',
    ktsat: 'a little',
    shuv: 'again',
    omrim: 'one says',
    kotvim: 'one writes',
    "mevat'im": 'one pronounces',
    hamila: 'the word',
    hazot: 'this (f)',
    laze: 'to this',
    dugma: 'an example',
    shakhakhti: 'I forgot',
    amarta: 'you said (to a man)',
    amart: 'you said (to a woman)',
    amarti: 'I said',
    hevanti: 'I understood',
    likhtov: 'to write',
    letargel: 'to practise',
    tirgul: 'practice',
    "tir'e": 'look (to a man)',
    "tir'i": 'look (to a woman)',
    matsati: 'I found',
    "hitgaʿgaʿti": 'I missed',
    ledaber: 'to speak',
    "la'asot": 'to do',
    lehipagesh: 'to meet',
    "be'ivrit": 'in Hebrew',
    "be'aravit": 'in Arabic',
    "be'anglit": 'in English',
    "ha'ivrit": 'the Hebrew',
    mishtaperet: 'improving (f)',
    mishtaper: 'improving (m)',
    smekha: 'happy (f)',
    sameakh: 'happy (m)',
    atsuva: 'sad (f)',
    atsuv: 'sad (m)',
    "re'eva": 'hungry (f)',
    "ra'ev": 'hungry (m)',
    "tsme'a": 'thirsty (f)',
    tsame: 'thirsty (m)',
    kar: 'cold',
    "mud'eget": 'worried (f)',
    "mud'ag": 'worried (m)',
    lekhutsa: 'nervous (f)',
    lakhuts: 'nervous (m)',
    "meshu'ememet": 'bored (f)',
    "meshu'amam": 'bored (m)',
    ose: 'doing (m)',
    osa: 'doing (f)',
    haya: 'was',
    asuk: 'busy (m)',
    asuka: 'busy (f)',
    gar: 'living (m)',
    gara: 'living (f)',
    itkha: 'with you (m)',
    itakh: 'with you (f)',
    panuy: 'free (m)',
    pnuya: 'free (f)',
    nipagesh: 'we will meet',
    "be'eizo": 'at which',
    bekhamesh: 'at five',
    yalla: "let's / come on",
    nelekh: "we'll go",
    "a'adken": 'I will update',
    elai: 'to me',
    akhar: 'after',
    kakh: 'so / thus — with akhar, "afterwards"',
    kekhi: 'take (to a woman)',
    otkha: 'you (m, as an object)',
    otakh: 'you (f, as an object)',
    oti: 'me (as an object)',
    matok: 'sweet (m)',
    metuka: 'sweet (f)',
    hakol: 'everything',
    "ge'a": 'proud (f)',
    "ge'e": 'proud (m)',
    bekha: 'in you (m)',
    bakh: 'in you (f)',
    bishvilkha: 'for you (m)',
    bishvilekh: 'for you (f)',
    tishan: 'sleep (to a man)',
    tishni: 'sleep (to a woman)',
    tihye: 'be (to a man)',
    tihyi: 'be (to a woman)',
    yihye: 'will be',
    levad: 'alone',
    mashehu: 'something',
    ten: 'give (to a man)',
    tni: 'give (to a woman)',
    noakh: 'comfortable',
    hazman: 'the time',
    kkhi: 'take (to a woman)',
    tagid: 'tell / say (to a man)',
    tagidi: 'tell / say (to a woman)',
    titen: 'give (to a man)',
    titni: 'give (to a woman)',
    tetaken: 'correct (to a man)',
    tetakni: 'correct (to a woman)',
    titkasher: 'call (to a man)',
    titkashri: 'call (to a woman)',
    kvar: 'already — with khozeret, "right back"',

    // --- telling somebody where to put themselves ----------------------------
    // The command decks under Directions. Every ending here is the listener's,
    // because these are things said to the person in front of you, so the pairs
    // are tagged "(to a woman)" / "(to a man)" throughout rather than (f) / (m).
    //
    // Two verbs English runs together are kept apart, because Hebrew keeps them
    // apart: tazuz moves the person spoken to, taziz moves a thing.
    "bo'i": 'come (to a woman)',
    bo: 'come (to a man)',
    "tavo'i": 'come (to a woman)',
    tavo: 'come (to a man)',
    "ta'ali": 'go up (to a woman)',
    "ta'ale": 'go up (to a man)',
    terdi: 'go down (to a woman)',
    tered: 'go down (to a man)',
    tazuzi: 'move yourself (to a woman)',
    tazuz: 'move yourself (to a man)',
    tazizi: 'move something (to a woman)',
    taziz: 'move something (to a man)',
    "ta'asi": 'do / make (to a woman)',
    "ta'ase": 'do / make (to a man)',
    "tisha'ari": 'stay (to a woman)',
    "tisha'er": 'stay (to a man)',
    "tisha'ani": 'lean (to a woman)',
    "tisha'en": 'lean (to a man)',
    tistakli: 'look (to a woman)',
    tistakel: 'look (to a man)',
    tarimi: 'lift (to a woman)',
    tarim: 'lift (to a man)',
    toridi: 'lower (to a woman)',
    torid: 'lower (to a man)',
    titafsi: 'grab (to a woman)',
    titpos: 'grab (to a man)',
    tithapkhi: 'turn over (to a woman)',
    tithapekh: 'turn over (to a man)',
    simi: 'put (to a woman)',
    sim: 'put (to a man)',
    tanikhi: 'put down (to a woman)',
    taniakh: 'put down (to a man)',
    "tavi'i": 'bring (to a woman)',
    tavi: 'bring (to a man)',
    tiftekhi: 'open (to a woman)',
    tiftakh: 'open (to a man)',
    tisgeri: 'close (to a woman)',
    tisgor: 'close (to a man)',

    // The things, places and manner words those commands point at.
    hayad: 'the hand / the arm',
    haregel: 'the leg / the foot',
    haraglayim: 'the legs / the feet',
    hagav: 'the back',
    hatsad: 'the side',
    latsad: 'to the side',
    hakarit: 'the pillow',
    hakise: 'the chair',
    lakatse: 'to the edge',
    lepo: 'to here',
    lakivun: 'towards',
    haze: 'this (m)',
    hasheni: 'the second — and so "the other one"',
    akharay: 'after me',
    "tsa'ad": 'a step',
    zkufa: 'upright (f)',
    zakuf: 'upright (m)',
    bizhirut: 'carefully',
    maspik: 'enough',
    pakhot: 'less',
    kol: 'all — with kakh, "so much"',
  },

  arabic: {
    // --- particles, pronouns and the small joining words ---------------------
    w: 'and',
    min: 'from / of',
    mish: 'not',
    mā: 'not — and "do not" before a command',
    ma: 'not',
    fī: 'there is',
    maʿ: 'with',
    ʿala: 'on',
    ʿan: 'from / about',
    baʿd: 'after',
    baʿdēn: 'later',
    hnīk: 'there',
    walla: 'or',
    wala: 'not even — with yhimmak, "never mind"',
    ktīr: 'a lot',
    shwayy: 'a little',
    kam: 'how many',
    mumkin: 'possible — "may I"',
    law: 'if — with samaḥt, "please"',
    in: 'if',
    yalla: 'come on',
    bāy: 'bye',

    // --- politeness and blessing ----------------------------------------------
    samaḥt: 'you allowed (m) — "please"',
    samaḥti: 'you allowed (f) — "please"',
    faḍlak: 'your favour (m)',
    faḍlik: 'your favour (f)',
    allah: 'God',
    shāʾ: 'willed',
    ybārik: 'may he bless',
    yiḥmīk: 'may he protect you (m)',
    yiḥmīki: 'may he protect you (f)',
    mubārak: 'blessed',
    khēr: 'goodness',
    nūr: 'light',
    ward: 'roses',
    ahl: 'people / family',
    sahlan: 'easy — with ahlan, "welcome"',
    'as-salāmu': 'the peace',
    'as-salām': 'the peace',
    'as-salāme': 'safety',
    'ʿas-salāme': 'in safety',
    ʿīd: 'feast',
    mīlād: 'birth',
    aḥlām: 'dreams',
    saʿīd: 'happy (m)',
    saʿīde: 'happy (f)',

    // --- times of day and the calendar -----------------------------------------
    ṣabāḥ: 'morning',
    masa: 'evening',
    tiṣbaḥ: 'may you wake (m)',
    tiṣbaḥi: 'may you wake (f)',
    nahārak: 'your day (m)',
    nahārik: 'your day (f)',
    sāʿa: 'hour',
    nuṣṣ: 'half',
    rubʿ: 'quarter',
    ʿuṭlet: 'holiday of',
    'iḍ-ḍuhur': 'the noon / midday',
    "waʾt": 'time',
    umūr: 'matters',

    // --- endings that carry who is being spoken to or about ---------------------
    ʿalēkum: 'upon you (pl)',
    fīk: 'in you (m)',
    fīki: 'in you (f)',
    bālak: 'your mind (m)',
    bālik: 'your mind (f)',
    ḥālak: 'your state (m)',
    ḥālik: 'your state (f)',
    ismo: 'its name',
    ismak: 'your name (m)',
    ismik: 'your name (f)',
    ʿumrak: 'your age (m)',
    ʿumrik: 'your age (f)',
    akhbārak: 'your news (m)',
    akhbārik: 'your news (f)',
    yhimmak: 'it concerns you (m)',
    yhimmik: 'it concerns you (f)',
    ʿēlti: 'my family',
    ukhti: 'my sister',
    akhūy: 'my brother',
    akh: 'brother',
    wlād: 'children',
    aṣḥāb: 'friends',
    ḥada: 'someone',
    māma: 'mom',
    mali: 'Mali — a name',

    // --- asking and answering ----------------------------------------------------
    tʿīd: 'you repeat (m)',
    tʿīdi: 'you repeat (f)',
    iḥki: 'speak',
    fāhme: 'understanding (f)',
    fāhem: 'understanding (m)',
    ʿarabi: 'Arabic — the language',
    ʿibri: 'Hebrew — the language',
    inglīzi: 'English — the language',
    yahūdi: 'Jewish (m)',
    yahūdiyye: 'Jewish (f)',
    ʿarabiyye: 'Arab (f)',
    mitjawwze: 'married (f)',
    mitjawwez: 'married (m)',
    bashūfak: 'I will see you (m)',
    bashūfik: 'I will see you (f)',
    dīr: 'mind (to a man)',
    dīri: 'mind (to a woman)',
    khud: 'take (to a man)',
    khudi: 'take (to a woman)',
    "ḥāses": 'feeling (m)',
    btilfiẓha: 'you pronounce it (m)',
    btilfiẓīha: 'you pronounce it (f)',
    "btiḥibbīh": 'you like it (f)',

    // --- the day's actions ---------------------------------------------------------
    btilbas: 'she puts on',
    byilbas: 'he puts on',
    tyāb: 'clothes',
    tyābha: 'her clothes',
    tyābu: 'his clothes',
    wijhha: 'her face',
    wijhu: 'his face',
    btfarresh: 'she brushes',
    byfarresh: 'he brushes',
    snān: 'teeth',
    snānha: 'her teeth',
    snānu: 'his teeth',
    btirjaʿ: 'she returns',
    byirjaʿ: 'he returns',
    shughul: 'work',
    "mūsīʾa": 'music',
    tilfizyōn: 'television',
    btiḥḍar: 'she watches',
    byiḥḍar: 'he watches',
    "btitlāʾa": 'she meets',
    "byitlāʾa": 'he meets',
    "btiʾoṣṣ": 'she cuts',
    "byiʾoṣṣ": 'he cuts',
    shaʿerha: 'her hair',
    shaʿro: 'his hair',
    ḍawāfirha: 'her nails',
    ḍawāfro: 'his nails',
    kurat: 'ball of',
    "ʾadam": 'foot',
    salle: 'basket',
    nādi: 'club',
    riyāḍi: 'sporting',

    // --- things around the house -----------------------------------------------------
    firshāyet: 'brush of',
    maʿjūn: 'paste',
    "waraʾ": 'paper',
    mazīl: 'remover of',
    "ʿaraʾ": 'sweat',
    shafret: 'blade of',
    "ḥalāʾa": 'shaving',
    mawād: 'materials',
    tanẓīf: 'cleaning',
    naẓāfe: 'cleaning',
    "wāʾi": 'guard against',
    shams: 'sun',
    ghurfet: 'room of',
    nōm: 'sleep',
    khazānet: 'cupboard of',
    ḥsāb: 'bill',
    "raʾam": 'number',
    ṣawtiyye: 'voice- (f)',
    mukālame: 'call',
    fāyte: 'missed (f)',
    wāy: 'wi- — with fāy, "wifi"',
    fāy: '-fi — with wāy, "wifi"',
    shaghghāl: 'working',
    kilmet: 'word of',
    sirr: 'secret',

    // --- feeling unwell -----------------------------------------------------------------
    marīḍa: 'ill (f)',
    marīḍ: 'ill (m)',
    rāsi: 'my head',
    baṭni: 'my stomach',
    byūjaʿ: 'it hurts',
    byūjaʿni: 'it hurts me',
    btūjaʿni: 'it hurts me',
    byūjaʿak: 'it hurts you (m)',
    byūjaʿik: 'it hurts you (f)',
    byliff: 'it spins — with rāsi, "I feel dizzy"',
    kaḥḥa: 'cough',

    // --- trouble and help ---------------------------------------------------------------
    ḥarīʾa: 'fire',
    inṣāb: 'got hurt',
    "tiʾlaʾ": 'you worry (m)',
    "tiʾlaʾi": 'you worry (f)',
    istanna: 'wait (to a man)',
    istanni: 'wait (to a woman)',
    'bish-shurṭa': 'the police',
    jawāz: 'permit — with safar, "passport"',
    safar: 'travel',
    asāʿdik: 'I help you (f)',

    // --- getting around -------------------------------------------------------------------
    liff: 'turn (to a man)',
    liffi: 'turn (to a woman)',
    imshi: 'go on',
    'ʿal-yamīn': 'to the right',
    'ʿash-shimāl': 'to the left',
    maḥaṭṭet: 'station of',
    bōṣal: 'do I get to',
    rakhīṣ: 'cheap',
    "aʾīso": 'I try it on',
    darrāje: 'bicycle',
    nāriyye: 'fiery — with darrāje, "motorcycle"',
    amān: 'safety',
    ṣāḥbet: 'owner (f) of',
    ʿāmlet: 'worker (f) of',
    ʿāmel: 'worker (m) of',

    // --- colours and describing things --------------------------------------------------------
    lōni: 'my colour',
    lōno: 'its colour',
    mufaḍḍal: 'favourite',
    sama: 'sky',
    ʿyūn: 'eyes',
    khuḍur: 'green (pl)',
    "ʾuṭṭa": 'cat (f)',

    // --- wanting, feeling, being able ------------------------------------------------------------
    bashūf: 'I see',
    baḥiss: 'I feel',
    baʿref: 'I know',
    baḥibb: 'I love',
    "baʾdar": 'I can',
    lāzim: 'must / need to',
    lāzimni: 'I need',
    "mushtāʾa": 'missing (f)',
    "mushtāʾ": 'missing (m)',
    bidha: 'she wants',
    bidna: 'we want',
    bidhom: 'they want',
    ākol: 'I eat',
    a: 'I ...',
    arūḥ: 'I go',
    biddo: 'he wants',
    "shūf": 'look (to a man)',
    shūfi: 'look (to a woman)',
    "laʾēt": 'I found',

    // --- the "I" form, where it only ever shows up inside a phrase -----------
    baḥḍar: 'I watch',
    "batlāʾa": 'I meet',
    "baʾuṣṣ": 'I cut',
    shaʿri: 'my hair',
    "ḍawāfri": 'my nails',
    btiḥki: 'you speak (to a man) / she speaks',

    // --- telling somebody to do something ------------------------------------
    // The Arabic imperative marks the person addressed twice over: once in the
    // verb ending and again in any possessive hanging off it, which is why
    // both halves of "wash your face" change.
    ilbasi: 'wear (to a woman)',
    ilbas: 'wear (to a man)',
    "tyābik": 'your clothes (to a woman)',
    "tyābak": 'your clothes (to a man)',
    ighsili: 'wash (to a woman)',
    ighsil: 'wash (to a man)',
    wijhik: 'your face (to a woman)',
    wijhak: 'your face (to a man)',
    farrshi: 'brush (to a woman)',
    farresh: 'brush (to a man)',
    "snānik": 'your teeth (to a woman)',
    "snānak": 'your teeth (to a man)',
    "rūḥi": 'go (to a woman)',
    "rūḥ": 'go (to a man)',
    "irjaʿi": 'come back (to a woman)',
    "irjaʿ": 'come back (to a man)',

    // --- the phrase decks ----------------------------------------------------
    // Palestinian Arabic carries the person in the ending far more than Hebrew
    // does, so most of these are tagged: (f) / (m) is the speaker's own, and
    // "(to a woman)" / "(to a man)" is the person being addressed.
    "ʿam": 'right now (before a verb)',
    lissa: 'still / not yet',
    hēk: 'like this / so',
    ishi: 'a thing / anything',
    kull: 'all / every',
    kān: 'was',
    "raḥ": 'will (before a verb)',
    "ykūn": 'be',
    "tamām": 'fine / all right',
    iza: 'if',
    elli: 'that / which',
    ayy: 'which',
    "ḥālan": 'right away',
    aktar: 'more',
    "aḥsan": 'better',
    "ṣirt": 'I became',
    "muhimm": 'important',
    "ṣaḥḥ": 'right / correct',
    "mithāl": 'an example',
    "tamrīn": 'practice',
    kalme: 'word',
    akel: 'food',
    "maʿnāha": 'its meaning',
    ism: 'name',
    "ʿibriti": 'my Hebrew',
    "ʿyūni": 'my eyes',
    "ʿalayy": 'on me / to me',
    fiyyi: 'me — after a verb like "call"',
    ilak: 'for you (m)',
    ilik: 'for you (f)',
    "maʿak": 'with you (m)',
    "maʿik": 'with you (f)',
    "yōmak": 'your day (m)',
    "yōmik": 'your day (f)',
    "waʾtak": 'your time (m)',
    "waʾtik": 'your time (f)',
    "laḥālak": 'by yourself (m)',
    "laḥālik": 'by yourself (f)',
    "āsfe": 'sorry (f)',
    "āsef": 'sorry (m)',
    "bardāne": 'cold (f)',
    "bardān": 'cold (m)',
    "ʾalʾāne": 'worried (f)',
    "ʾalʾān": 'worried (m)',
    mitwattre: 'nervous (f)',
    mitwattir: 'nervous (m)',
    "zahʾāne": 'bored (f)',
    "zahʾān": 'bored (m)',
    "fakhūra": 'proud (f)',
    "fakhūr": 'proud (m)',
    "sākne": 'living (f)',
    "sāken": 'living (m)',
    "mashghūle": 'busy (f)',
    "mashghūl": 'busy (m)',
    "ḥāsse": 'feeling (f)',
    "ḥāsis": 'feeling (m)',
    "baẓunn": 'I think',
    "bniḥki": 'we say',
    "niḥki": 'we talk',
    "baḥki": 'I speak',
    "batʿallam": 'I am learning',
    "batḥassan": 'I am improving',
    bafakkir: 'I am thinking',
    "barjaʿ": 'I come back',
    atmarran: 'I practise',
    "nitʾābal": 'we meet',
    "nrūḥ": "we'll go",
    "nsīt": 'I forgot',
    "smiʿtak": 'I heard you (m)',
    "smiʿtik": 'I heard you (f)',
    "ʾulti": 'you said (to a woman)',
    "ʾultha": 'I said it',
    "btiḥibb": 'you like (to a man)',
    "btiḥibbi": 'you like (to a woman)',
    "btiḥibbo": 'you like it (to a man)',
    "btiḥibbī": 'you like it (to a woman)',
    ti: 'you ...',
    "tiʿmal": 'you do (to a man)',
    "tiʿmali": 'you do (to a woman)',
    btinkatib: 'it is written',
    "btinlafaẓ": 'it is pronounced',
    "biyūjaʿ": 'it hurts',
    "biyūjaʿak": 'it hurts you (m)',
    "biyūjaʿik": 'it hurts you (f)',
    "shwayyet": 'a little of',
    "ʿīdha": 'repeat it (to a man)',
    "ʿīdīha": 'repeat it (to a woman)',
    tiktibha: 'you write it (to a man)',
    "tiktibīha": 'you write it (to a woman)',
    "taʿṭīni": 'you give me',
    "ṣaḥḥiḥli": 'correct me (to a man)',
    "ṣaḥḥiḥīli": 'correct me (to a woman)',
    "khallīni": 'let me',
    "asāʿdak": 'help you (m)',
    "khōd": 'take (to a man)',
    "khōdi": 'take (to a woman)',
    "ʾilli": 'tell me (to a man)',
    "ʾūlīli": 'tell me (to a woman)',
    "tizʿal": 'be sad (to a man)',
    "tizʿali": 'be sad (to a woman)',

    // --- telling somebody where to put themselves ----------------------------
    // The command decks under Directions. As with the Hebrew, the ending is the
    // listener's throughout — and Palestinian marks that listener twice over,
    // once in the verb and again in whatever hangs off it, so "lift your head"
    // changes in both halves: irfaʿi rāsik beside irfaʿ rāsak.
    //
    // tḥarrak moves the person spoken to; ḥarrik moves a thing. They are the
    // same root, and the pair below is the only place a learner can see that.
    "taʿāli": 'come (to a woman)',
    "taʿāl": 'come (to a man)',
    "tḥarraki": 'move yourself (to a woman)',
    "tḥarrak": 'move yourself (to a man)',
    "ḥarrki": 'move something (to a woman)',
    "ḥarrik": 'move something (to a man)',
    "titḥarraki": 'you move (f) — with ma, "do not move"',
    "titḥarrak": 'you move (m) — with ma, "do not move"',
    "ḍalli": 'stay (to a woman)',
    "ḍall": 'stay (to a man)',
    "zīḥi": 'shift over (to a woman)',
    "zīḥ": 'shift over (to a man)',
    "mīli": 'lean (to a woman)',
    "mīl": 'lean (to a man)',
    "inḥani": 'bend down — said the same way to anybody',
    "ʿaddli": 'straighten (to a woman)',
    "ʿaddil": 'straighten (to a man)',
    "irfaʿi": 'lift (to a woman)',
    "irfaʿ": 'lift (to a man)',
    "nazzli": 'lower (to a woman)',
    "nazzil": 'lower (to a man)',
    "shīli": 'pick up (to a woman)',
    "shīl": 'pick up (to a man)',
    "ḥuṭṭi": 'put (to a woman)',
    "ḥuṭṭ": 'put (to a man)',
    "jībi": 'bring (to a woman)',
    "jīb": 'bring (to a man)',
    "iftaḥi": 'open (to a woman)',
    "iftaḥ": 'open (to a man)',
    "sakkri": 'close (to a woman)',
    "sakkir": 'close (to a man)',
    "iʾlibi": 'flip over (to a woman)',
    "iʾlib": 'flip over (to a man)',
    "aʿṭīni": 'give me',

    // The body and the things the commands point at, each ending marking who
    // is being spoken to rather than who owns it.
    "rāsik": 'your head (to a woman)',
    "rāsak": 'your head (to a man)',
    "īdik": 'your hand (to a woman)',
    "īdak": 'your hand (to a man)',
    "īdi": 'my hand',
    "ijrik": 'your foot / leg (to a woman)',
    "ijrak": 'your foot / leg (to a man)',
    "rijlēki": 'your feet (to a woman)',
    "rijlēk": 'your feet (to a man)',
    "kursīki": 'your chair (to a woman)',
    "kursīk": 'your chair (to a man)',
    "rāḥtik": 'your ease (to a woman) — "your time"',
    "rāḥtak": 'your ease (to a man) — "your time"',
    "ʿa-janbik": 'onto your side (to a woman)',
    "ʿa-janbak": 'onto your side (to a man)',
    "ʿa-ẓahrik": 'onto your back (to a woman)',
    "ʿa-ẓahrak": 'onto your back (to a man)',
    "ʿa-baṭnik": 'onto your stomach (to a woman)',
    "ʿa-baṭnak": 'onto your stomach (to a man)',

    // The places and the manner words.
    "hnāk": 'there',
    "la-hnāk": 'to there',
    "ʿal-jiha": 'to the side / direction',
    "it-tānye": 'the second (f) — and so "the other one"',
    "khuṭwe": 'a step',
    "mashi": 'walking — with kammil, "keep walking"',
    "ʿadl": 'straight / upright',
    "shway": 'a little',
    "kamān": 'more / another',
    "ʾaʾall": 'less',
    "bikaffi": 'it is enough',
    "warāy": 'behind me',
  },
};
