/**
 * Word-by-word meanings for the transliterations, so a learner can hover any
 * word in a phrase and see what that word is doing there.
 *
 * Only the words the starter table does not already define on its own live
 * here. A card whose transliteration is a single word is its own definition —
 * "khamse" is glossed by the card that teaches five — and `src/utils/glossary`
 * reads those straight out of the seed. What is left is everything that only
 * ever appears inside a phrase: particles, prepositions, possessive endings,
 * conjugated verbs and the first half of a construct pair.
 *
 * House style for an entry:
 *
 * - Say what the *word* means, not what the phrase means. `ṣabāḥ` is "morning",
 *   even though the only card it appears on is "good morning".
 * - Mark who a form belongs to in parentheses — "(f)", "(to a man)" — because
 *   these two languages carry that in the ending, which is exactly what a
 *   learner is hovering the word to see.
 * - Keep it to a few words. This is read in a tooltip, over a card, mid-drill.
 */

export type GlossLanguage = 'hebrew' | 'arabic';

/**
 * Prefixes written onto the next word with a hyphen.
 *
 * `…` stands in for the stem's own meaning, so "ve-arba" reads as "and four"
 * without the table listing every numeral twice. Only hyphenated prefixes are
 * split off: a bare `la` is the Hebrew word for "to her", and `min` is a word
 * in its own right, so neither may be treated as a piece of something longer.
 */
export const CLITICS: Record<GlossLanguage, Record<string, string>> = {
  hebrew: {
    ve: 'and …',
    v: 'and …',
    u: 'and …',
    ha: 'the …',
    be: 'in …',
    ba: 'in the …',
    la: 'to the …',
    le: 'to …',
    mi: 'from …',
    me: 'from …',
    she: 'that …',
    ke: 'like …',
  },
  arabic: {
    w: 'and …',
    wa: 'and …',
    u: 'and …',
    // The article, and the shapes it takes when it assimilates to the letter
    // after it: el-bēt, but en-nūr and es-sāʿa.
    el: 'the …',
    il: 'the …',
    al: 'the …',
    en: 'the …',
    es: 'the …',
    esh: 'the …',
    ed: 'the …',
    et: 'the …',
    as: 'the …',
    ash: 'the …',
    la: 'to …',
    lal: 'to the …',
    bi: 'with …',
    bil: 'in the …',
    bish: 'in the …',
    ʿa: 'at …',
    ʿal: 'at the …',
    ʿas: 'at the …',
    ʿash: 'at the …',
  },
};

/**
 * The hand-written half of the glossary, keyed by the lower-cased word exactly
 * as the starter table romanises it.
 *
 * An entry here beats the meaning derived from a single-word card, because it
 * is written about the word itself where the derived one can only repeat
 * whatever the whole card happened to mean.
 */
export const CURATED_GLOSSES: Record<GlossLanguage, Record<string, string>> = {
  hebrew: {
    // --- particles, pronouns and the small joining words --------------------
    yesh: 'there is / has',
    ein: 'there is no',
    li: 'to me — with yesh, "I have"',
    la: 'to her — with yesh, "she has"',
    lo: 'not / no',
    al: 'do not (before a command)',
    o: 'or',
    im: 'with',
    gam: 'also',
    kan: 'here',
    ʿal: 'on / about',
    eize: 'which / what',
    // Also the imperative "get up", which a card teaches; a learner meeting it
    // inside a phrase is asking about the question word every time.
    kama: 'how much / how many',
    "me'od": 'very',
    "me'eifo": 'where from',
    mikan: 'from here',
    lesham: 'to there',
    akharei: 'after',
    efshar: 'is it possible / may I',
    "le'at": 'slowly',

    // --- endings that carry who is being spoken to or about -----------------
    lekha: 'to you (m)',
    lakh: 'to you (f)',
    elekha: 'to you (m)',
    elayikh: 'to you (f)',
    alekha: 'upon you (m)',
    alayikh: 'upon you (f)',
    alay: 'on me / for me',
    ʿalekhem: 'upon you (pl)',
    ʿatsmekha: 'yourself (m)',
    ʿatsmekh: 'yourself (f)',
    shlomkha: 'your wellbeing (m)',
    shlomekh: 'your wellbeing (f)',
    shelanu: 'our',
    shelakhem: 'your (m pl)',
    shelakhen: 'your (f pl)',
    shelahem: 'their (m)',
    shelahen: 'their (f)',
    akhi: 'my brother',
    akhoti: 'my sister',

    // --- times of day, days and the calendar --------------------------------
    boker: 'morning',
    tsohorayim: 'noon',
    erev: 'evening',
    layla: 'night',
    yom: 'day',
    tovim: 'good (pl)',
    maksim: 'delightful',
    "na'im": 'pleasant',
    naʿim: 'pleasant',
    nishmaʿ: 'is heard',
    khalomot: 'dreams',
    paz: 'gold — here "sweet"',
    rishon: 'first',
    sheni: 'second',
    shlishi: 'third',
    "revi'i": 'fourth',
    khamishi: 'fifth',
    shishi: 'sixth',
    sof: 'end',
    "hasha'a": 'the hour / the time',
    hitkhil: 'it began',
    zman: 'time',

    // --- greetings and set phrases ------------------------------------------
    barukh: 'blessed (m)',
    brukha: 'blessed (f)',
    haba: 'the one coming (m)',
    "haba'a": 'the one coming (f)',
    hashav: 'the one returning (m)',
    hashava: 'the one returning (f)',
    hashem: 'God — literally "the Name"',
    elohim: 'God',
    yishmor: 'may he protect',
    tishmor: 'guard / keep (to a man)',
    tishmeri: 'guard / keep (to a woman)',
    "be'ezrat": 'with the help of',
    mazal: 'luck',
    huledet: 'birth',
    khag: 'festival',
    "refu'a": 'healing',
    shlema: 'complete (f)',

    // --- asking and answering -----------------------------------------------
    "kor'im": 'they call — with li, "my name is"',
    mali: 'Mali — a name',
    tukhal: 'can you (m)',
    tukhli: 'can you (f)',
    lakhzor: 'to repeat / go back',
    daber: 'speak (to a man)',
    dabri: 'speak (to a woman)',
    "lish'ol": 'to ask',
    ivrit: 'Hebrew — the language',
    aravit: 'Arabic — the language',
    anglit: 'English — the language',
    yehudi: 'Jewish (m)',
    yehudiya: 'Jewish (f)',
    aravi: 'Arab (m)',
    araviya: 'Arab (f)',

    // --- family and people ---------------------------------------------------
    zug: 'pair — with bat or ben, "partner"',
    akhim: 'brothers',
    yeladim: 'children',
    khaverim: 'friends',
    krovei: 'relatives of',
    hamishpakha: 'the family',
    "nesu'a": 'married (f)',
    nasui: 'married (m)',
    mishehu: 'someone',
    orekhet: 'arranger (f) — with din, "lawyer"',
    orekh: 'arranger (m) — with din, "lawyer"',
    din: 'law',

    // --- the day's actions ----------------------------------------------------
    okhelet: 'eats (f)',
    okhel: 'eats (m)',
    arukhat: 'meal of',
    metsakhtsakhat: 'brushes (f)',
    metsakhtseakh: 'brushes (m)',
    shinayim: 'teeth',
    mivreshet: 'brush',
    mishkhat: 'paste of',
    khozeret: 'returns (f)',
    khozer: 'returns (m)',
    habayta: 'homewards',
    habayit: 'the house',
    babayit: 'in the house',
    beit: 'house of',
    "la'avoda": 'to work',
    muzika: 'music',
    makshiva: 'listens (f)',
    makshiv: 'listens (m)',
    nifgeshet: 'meets (f)',
    nifgash: 'meets (m)',
    gozeret: 'cuts (f)',
    gozer: 'cuts (m)',
    tsiporanayim: 'nails',
    khadar: 'room of',
    kosher: 'fitness',
    ambatya: 'bath',
    shena: 'sleep',
    bgadim: 'clothes',
    "shi'urei": 'lessons of',

    // --- things around the house ----------------------------------------------
    niyar: 'paper',
    toalet: 'toilet',
    giluakh: 'shaving',
    khomrei: 'materials of',
    nikuy: 'cleaning',
    mekhonat: 'machine of',
    hagana: 'protection',
    adama: 'earth — with tapuakh, "potato"',
    hakheshbon: 'the bill',
    nayad: 'portable',
    mispar: 'number',
    kolit: 'voice- (f)',
    sikha: 'call',
    "ne'enta": 'was answered',

    // --- feeling unwell --------------------------------------------------------
    khola: 'ill (f)',
    khole: 'ill (m)',
    kholim: 'the sick',
    hakholim: 'the sick',
    mirkakhat: 'pharmacy — in beit mirkakhat',
    "ko'ev": 'hurts (m)',
    "ko'evet": 'hurts (f)',
    harosh: 'the head',
    habeten: 'the stomach',
    "shi'ul": 'cough',
    skharkhoret: 'dizziness',
    margisha: 'feel (f)',
    margish: 'feel (m)',

    // --- trouble and help -------------------------------------------------------
    "ta'azor": 'help (to a man)',
    "ta'azri": 'help (to a woman)',
    laʿazor: 'to help',
    lamishtara: 'to the police',
    titkasheri: 'call (to a woman)',
    srefa: 'fire',
    nifga: 'is hurt',
    "le'ibud": 'lost — with halakhti, "I got lost"',
    "tid'ag": 'worry (m)',
    "tid'agi": 'worry (f)',
    khake: 'wait (to a man)',
    khaki: 'wait (to a woman)',
    "te'udat": 'certificate of',
    zehut: 'identity',

    // --- getting around ----------------------------------------------------------
    takhanat: 'station of',
    pne: 'turn (to a man)',
    pni: 'turn (to a woman)',
    sa: 'drive on (to a man)',
    "si'i": 'drive on (to a woman)',
    haramzor: 'the traffic light',
    pkak: 'stopper — with tnua, "traffic jam"',
    tnua: 'traffic',
    khagorat: 'belt of',
    betikhut: 'safety',
    sde: 'field of',
    "te'ufa": 'aviation',
    "magi'im": 'one gets to',
    knesset: 'assembly — in beit knesset, "synagogue"',
    ole: 'costs',
    limdod: 'to try on',
    mekhonit: 'car',

    // --- colours and describing things ---------------------------------------------
    tseva: 'colour',
    "ha'ahuv": 'the favourite',
    hashamayim: 'the sky',
    kkhulim: 'blue (pl)',
    einayim: 'eyes',
    yerukot: 'green (f pl)',
    zayit: 'olive',
    gur: 'cub — with klavim, "puppy"',
    klavim: 'dogs',

    // --- wanting, feeling, being able ------------------------------------------------
    rotsot: 'want (f pl)',
    rotsim: 'want (m pl)',
    yekhola: 'can (f)',
    yakhol: 'can (m)',
    "le'ekhol": 'to eat',
    lalekhet: 'to go',
    "mitga'aga'at": 'missing (f)',
    "mitga'age'a": 'missing (m)',

    // --- telling somebody to do something ------------------------------------
    // Everyday Hebrew gives its orders in the future tense, and the ending is
    // the person being told — which is the whole point of the cards these
    // words come from.
    tishtefi: 'wash (to a woman)',
    tishtof: 'wash (to a man)',
    tetsakhtsekhi: 'brush (to a woman)',
    tetsakhtseakh: 'brush (to a man)',
    tokhli: 'eat (to a woman)',
    tokhal: 'eat (to a man)',
    takhzeri: 'come back (to a woman)',
    takhzor: 'come back (to a man)',
    lekh: 'go (to a man)',
    lishon: 'to sleep',
  },

  arabic: {
    // --- particles, pronouns and the small joining words ---------------------
    w: 'and',
    min: 'from / of',
    mish: 'not',
    mā: 'not — and "do not" before a command',
    ma: 'not',
    fī: 'there is',
    maʿ: 'with',
    ʿala: 'on',
    ʿan: 'from / about',
    baʿd: 'after',
    baʿdēn: 'later',
    hnīk: 'there',
    walla: 'or',
    wala: 'not even — with yhimmak, "never mind"',
    ktīr: 'a lot',
    shwayy: 'a little',
    kam: 'how many',
    mumkin: 'possible — "may I"',
    law: 'if — with samaḥt, "please"',
    in: 'if',
    yalla: 'come on',
    bāy: 'bye',

    // --- politeness and blessing ----------------------------------------------
    samaḥt: 'you allowed (m) — "please"',
    samaḥti: 'you allowed (f) — "please"',
    faḍlak: 'your favour (m)',
    faḍlik: 'your favour (f)',
    allah: 'God',
    shāʾ: 'willed',
    ybārik: 'may he bless',
    yiḥmīk: 'may he protect you (m)',
    yiḥmīki: 'may he protect you (f)',
    mubārak: 'blessed',
    khēr: 'goodness',
    nūr: 'light',
    ward: 'roses',
    ahl: 'people / family',
    sahlan: 'easy — with ahlan, "welcome"',
    'as-salāmu': 'the peace',
    'as-salām': 'the peace',
    'as-salāme': 'safety',
    'ʿas-salāme': 'in safety',
    ʿīd: 'feast',
    mīlād: 'birth',
    aḥlām: 'dreams',
    saʿīd: 'happy (m)',
    saʿīde: 'happy (f)',

    // --- times of day and the calendar -----------------------------------------
    ṣabāḥ: 'morning',
    masa: 'evening',
    tiṣbaḥ: 'may you wake (m)',
    tiṣbaḥi: 'may you wake (f)',
    nahārak: 'your day (m)',
    nahārik: 'your day (f)',
    sāʿa: 'hour',
    nuṣṣ: 'half',
    rubʿ: 'quarter',
    ʿuṭlet: 'holiday of',
    waqt: 'time',
    umūr: 'matters',

    // --- endings that carry who is being spoken to or about ---------------------
    ʿalēkum: 'upon you (pl)',
    fīk: 'in you (m)',
    fīki: 'in you (f)',
    bālak: 'your mind (m)',
    bālik: 'your mind (f)',
    ḥālik: 'your state (f)',
    ismak: 'your name (m)',
    ismik: 'your name (f)',
    ʿumrak: 'your age (m)',
    ʿumrik: 'your age (f)',
    akhbārak: 'your news (m)',
    akhbārik: 'your news (f)',
    yhimmak: 'it concerns you (m)',
    yhimmik: 'it concerns you (f)',
    ʿēlti: 'my family',
    ukhti: 'my sister',
    akhūy: 'my brother',
    akh: 'brother',
    wlād: 'children',
    aṣḥāb: 'friends',
    ḥada: 'someone',
    māma: 'mom',
    mali: 'Mali — a name',

    // --- asking and answering ----------------------------------------------------
    tʿīd: 'you repeat (m)',
    tʿīdi: 'you repeat (f)',
    iḥki: 'speak',
    fāhme: 'understanding (f)',
    fāhem: 'understanding (m)',
    ʿarabi: 'Arabic — the language',
    ʿibri: 'Hebrew — the language',
    inglīzi: 'English — the language',
    yahūdi: 'Jewish (m)',
    yahūdiyye: 'Jewish (f)',
    ʿarabiyye: 'Arab (f)',
    mitjawwze: 'married (f)',
    mitjawwez: 'married (m)',
    bashūfak: 'I will see you (m)',
    bashūfik: 'I will see you (f)',
    dīr: 'mind (to a man)',
    dīri: 'mind (to a woman)',

    // --- the day's actions ---------------------------------------------------------
    btilbas: 'she puts on',
    byilbas: 'he puts on',
    tyāb: 'clothes',
    tyābha: 'her clothes',
    tyābu: 'his clothes',
    wijhha: 'her face',
    wijhu: 'his face',
    btfarresh: 'she brushes',
    byfarresh: 'he brushes',
    snān: 'teeth',
    snānha: 'her teeth',
    snānu: 'his teeth',
    btirjaʿ: 'she returns',
    byirjaʿ: 'he returns',
    shughul: 'work',
    mūsīqa: 'music',
    tilfizyōn: 'television',
    btiḥḍar: 'she watches',
    byiḥḍar: 'he watches',
    btitlāqa: 'she meets',
    byitlāqa: 'he meets',
    btiqoṣṣ: 'she cuts',
    byiqoṣṣ: 'he cuts',
    shaʿerha: 'her hair',
    shaʿro: 'his hair',
    ḍawāfirha: 'her nails',
    ḍawāfro: 'his nails',
    kurat: 'ball of',
    qadam: 'foot',
    salle: 'basket',
    nādi: 'club',
    riyāḍi: 'sporting',

    // --- things around the house -----------------------------------------------------
    firshāyet: 'brush of',
    maʿjūn: 'paste',
    waraq: 'paper',
    mazīl: 'remover of',
    ʿaraq: 'sweat',
    shafret: 'blade of',
    ḥalāqa: 'shaving',
    mawād: 'materials',
    tanẓīf: 'cleaning',
    naẓāfe: 'cleaning',
    wāqi: 'guard against',
    shams: 'sun',
    ghurfet: 'room of',
    nōm: 'sleep',
    khazānet: 'cupboard of',
    ḥsāb: 'bill',
    raqam: 'number',
    ṣawtiyye: 'voice- (f)',
    mukālame: 'call',
    fāyte: 'missed (f)',
    wāy: 'wi- — with fāy, "wifi"',
    fāy: '-fi — with wāy, "wifi"',
    shaghghāl: 'working',
    kilmet: 'word of',
    sirr: 'secret',

    // --- feeling unwell -----------------------------------------------------------------
    marīḍa: 'ill (f)',
    marīḍ: 'ill (m)',
    rāsi: 'my head',
    baṭni: 'my stomach',
    byūjaʿ: 'it hurts',
    byūjaʿni: 'it hurts me',
    btūjaʿni: 'it hurts me',
    byūjaʿak: 'it hurts you (m)',
    byūjaʿik: 'it hurts you (f)',
    byliff: 'it spins — with rāsi, "I feel dizzy"',
    kaḥḥa: 'cough',

    // --- trouble and help ---------------------------------------------------------------
    ḥarīʾa: 'fire',
    inṣāb: 'got hurt',
    tiqlaq: 'you worry (m)',
    tiqlaqi: 'you worry (f)',
    istanna: 'wait (to a man)',
    istanni: 'wait (to a woman)',
    'bish-shurṭa': 'the police',
    jawāz: 'permit — with safar, "passport"',
    safar: 'travel',
    asāʿdik: 'I help you (f)',

    // --- getting around -------------------------------------------------------------------
    liff: 'turn (to a man)',
    liffi: 'turn (to a woman)',
    imshi: 'go on',
    'ʿal-yamīn': 'to the right',
    'ʿash-shimāl': 'to the left',
    maḥaṭṭet: 'station of',
    bōṣal: 'do I get to',
    rakhīṣ: 'cheap',
    aqīso: 'I try it on',
    darrāje: 'bicycle',
    nāriyye: 'fiery — with darrāje, "motorcycle"',
    amān: 'safety',
    ṣāḥbet: 'owner (f) of',
    ʿāmlet: 'worker (f) of',
    ʿāmel: 'worker (m) of',

    // --- colours and describing things --------------------------------------------------------
    lōni: 'my colour',
    lōno: 'its colour',
    mufaḍḍal: 'favourite',
    sama: 'sky',
    ʿyūn: 'eyes',
    khuḍur: 'green (pl)',
    quṭṭa: 'cat (f)',

    // --- wanting, feeling, being able ------------------------------------------------------------
    bashūf: 'I see',
    baḥiss: 'I feel',
    baʿref: 'I know',
    baḥibb: 'I love',
    baqdar: 'I can',
    lāzimni: 'I need',
    mushtāqa: 'missing (f)',
    mushtāq: 'missing (m)',
    bidha: 'she wants',
    bidna: 'we want',
    bidhom: 'they want',
    ākol: 'I eat',
    arūḥ: 'I go',
    biddo: 'he wants',

    // --- the "I" form, where it only ever shows up inside a phrase -----------
    baḥḍar: 'I watch',
    batlāqa: 'I meet',
    baquṣṣ: 'I cut',
    shaʿri: 'my hair',
    "ḍawāfri": 'my nails',
    btiḥki: 'you speak (to a man) / she speaks',

    // --- telling somebody to do something ------------------------------------
    // The Arabic imperative marks the person addressed twice over: once in the
    // verb ending and again in any possessive hanging off it, which is why
    // both halves of "wash your face" change.
    ilbasi: 'wear (to a woman)',
    ilbas: 'wear (to a man)',
    "tyābik": 'your clothes (to a woman)',
    "tyābak": 'your clothes (to a man)',
    ighsili: 'wash (to a woman)',
    ighsil: 'wash (to a man)',
    wijhik: 'your face (to a woman)',
    wijhak: 'your face (to a man)',
    farrshi: 'brush (to a woman)',
    farresh: 'brush (to a man)',
    "snānik": 'your teeth (to a woman)',
    "snānak": 'your teeth (to a man)',
    "rūḥi": 'go (to a woman)',
    "rūḥ": 'go (to a man)',
    "irjaʿi": 'come back (to a woman)',
    "irjaʿ": 'come back (to a man)',
  },
};
